PACKAGE          = Combination
PACKAGE_DEP 	 = CalibrationDataInterface Asg_Boost cppunit Asg_root

PACKAGE_CXXFLAGS =
PACKAGE_LDFLAGS  = 
PACKAGE_PRELOAD  = RooFit boost_regex

PACKAGE_PEDANTIC = 1

include $(ROOTCOREDIR)/Makefile-common
